const sounds = {
    // voiced consonants
    genkyu: require('../assets/sounds/voicedconsonant/01-genkyu-M.mp3'),
    kenkyu: require('../assets/sounds/voicedconsonant/02-kenkyu-M.mp3'),
    goudou: require('../assets/sounds/voicedconsonant/03-goudou-F.mp3'),
    koudou: require('../assets/sounds/voicedconsonant/04-koudou-F.mp3'),
    gantan: require('../assets/sounds/voicedconsonant/05-gantan-M.mp3'),
    kantan: require('../assets/sounds/voicedconsonant/06-kantan-M.mp3'),
    daigakumei: require('../assets/sounds/voicedconsonant/07-daigakumei-M.mp3'),
    daikakumei: require('../assets/sounds/voicedconsonant/08-daikakumei-M.mp3'),
    shougai: require('../assets/sounds/voicedconsonant/09-shougai-F.mp3'),
    shoukai: require('../assets/sounds/voicedconsonant/10-shoukai-F.mp3'),
    kangoku: require('../assets/sounds/voicedconsonant/11-kangoku-F.mp3'),
    kankoku: require('../assets/sounds/voicedconsonant/12-kankoku-F.mp3'),
    gikai: require('../assets/sounds/voicedconsonant/13-gikai-F.mp3'),
    kikai: require('../assets/sounds/voicedconsonant/14-kikai-F.mp3'),
    guchi: require('../assets/sounds/voicedconsonant/15-guchi-M.mp3'),
    kuchi: require('../assets/sounds/voicedconsonant/16-kuchi-M.mp3'),
    gaikoku: require('../assets/sounds/voicedconsonant/17-gaikoku-F.mp3'),
    kaikoku: require('../assets/sounds/voicedconsonant/18-kaikoku-F.mp3'),
    // long vowels
    biru: require('../assets/sounds/longvowel/01-biru-F.mp3'),
    biiru: require('../assets/sounds/longvowel/02-biiru-F.mp3'),
    syujin: require('../assets/sounds/longvowel/03-syujin-F.mp3'),
    syuujin: require('../assets/sounds/longvowel/04-syuujin-F.mp3'),
    soko: require('../assets/sounds/longvowel/05-soko-F.mp3'),
    sooko: require('../assets/sounds/longvowel/06-sooko-F.mp3'),
    ojisan: require('../assets/sounds/longvowel/07-ojisan-F.mp3'),
    ojiisan: require('../assets/sounds/longvowel/08-ojiisan-F.mp3'),
    sakka: require('../assets/sounds/longvowel/09-sakka-M.mp3'),
    sakkaa: require('../assets/sounds/longvowel/10-sakkaa-M.mp3'),
    kare: require('../assets/sounds/longvowel/11-kare-M.mp3'),
    karee: require('../assets/sounds/longvowel/12-karee-M.mp3'),
    kibo: require('../assets/sounds/longvowel/13-kibo-M.mp3'),
    kiboo: require('../assets/sounds/longvowel/14-kiboo-M.mp3'),
    kutsu: require('../assets/sounds/longvowel/15-kutsu-F.mp3'),
    kutsuu: require('../assets/sounds/longvowel/16-kutsuu-F.mp3'),
    sato: require('../assets/sounds/longvowel/17-sato-M.mp3'),
    satoo: require('../assets/sounds/longvowel/18-satoo-M.mp3'),
    kondo: require('../assets/sounds/longvowel/19-kondo-M.mp3'),
    kondoo: require('../assets/sounds/longvowel/20-kondoo-M.mp3'),
}

export default sounds