const sounds = {
    // audio feedback
    correct: require('../assets/sounds/feedback/Correct_Answer.mp3'),
    incorrect: require('../assets/sounds/feedback/Wrong_Buzzer.mp3'),
    // voiced consonants
    genkyu: require('../assets/sounds/voicedconsonant/01-genkyu-M.mp3'),
    kenkyu: require('../assets/sounds/voicedconsonant/02-kenkyu-M.mp3'),
    goudou: require('../assets/sounds/voicedconsonant/03-goudou-F.mp3'),
    koudou: require('../assets/sounds/voicedconsonant/04-koudou-F.mp3'),
    gantan: require('../assets/sounds/voicedconsonant/05-gantan-M.mp3'),
    kantan: require('../assets/sounds/voicedconsonant/06-kantan-M.mp3'),
    daigakumei: require('../assets/sounds/voicedconsonant/07-daigakumei-M.mp3'),
    daikakumei: require('../assets/sounds/voicedconsonant/08-daikakumei-M.mp3'),
    shougai: require('../assets/sounds/voicedconsonant/09-shougai-F.mp3'),
    shoukai: require('../assets/sounds/voicedconsonant/10-shoukai-F.mp3'),
    kangoku: require('../assets/sounds/voicedconsonant/11-kangoku-F.mp3'),
    kankoku: require('../assets/sounds/voicedconsonant/12-kankoku-F.mp3'),
    gikai: require('../assets/sounds/voicedconsonant/13-gikai-F.mp3'),
    kikai: require('../assets/sounds/voicedconsonant/14-kikai-F.mp3'),
    guchi: require('../assets/sounds/voicedconsonant/15-guchi-M.mp3'),
    kuchi: require('../assets/sounds/voicedconsonant/16-kuchi-M.mp3'),
    gaikoku: require('../assets/sounds/voicedconsonant/17-gaikoku-F.mp3'),
    kaikoku: require('../assets/sounds/voicedconsonant/18-kaikoku-F.mp3'),
    tokidoki: require('../assets/sounds/voicedconsonant/01-1-tokidoki-F.mp3'),
    dokidoki: require('../assets/sounds/voicedconsonant/01-2-dokidoki-F.mp3'),
    taigaku: require('../assets/sounds/voicedconsonant/02-1-taigaku-F.mp3'),
    daigaku: require('../assets/sounds/voicedconsonant/02-2-daigaku-F.mp3'),
    kin: require('../assets/sounds/voicedconsonant/03-1-kin-F.mp3'),
    gin: require('../assets/sounds/voicedconsonant/03-2-gin-F.mp3'),
    piza: require('../assets/sounds/voicedconsonant/04-1-piza-F.mp3'),
    biza: require('../assets/sounds/voicedconsonant/04-2-biza-F.mp3'),
    tenki: require('../assets/sounds/voicedconsonant/05-1-tenki-F.mp3'),
    denki: require('../assets/sounds/voicedconsonant/05-2-denki-F.mp3'),
    kaki: require('../assets/sounds/voicedconsonant/06-1-kaki-F.mp3'),
    kagi: require('../assets/sounds/voicedconsonant/06-2-kagi-F.mp3'),
    tsuki: require('../assets/sounds/voicedconsonant/07-1-tsuki-F.mp3'),
    tsugi: require('../assets/sounds/voicedconsonant/07-2-tsugi-F.mp3'),
    pin: require('../assets/sounds/voicedconsonant/08-1-pin-F.mp3'),
    bin: require('../assets/sounds/voicedconsonant/08-2-bin-F.mp3'),
    shinzou: require('../assets/sounds/voicedconsonant/09-1-shinzou-F.mp3'),
    jinzou: require('../assets/sounds/voicedconsonant/09-2-jinzou-F.mp3'),
    koma: require('../assets/sounds/voicedconsonant/10-1-koma-F.mp3'),
    goma: require('../assets/sounds/voicedconsonant/10-2-goma-F.mp3'),
    shiken: require('../assets/sounds/voicedconsonant/11-1-shiken-F.mp3'),
    jiken: require('../assets/sounds/voicedconsonant/11-2-jiken-F.mp3'),
    kaisya: require('../assets/sounds/voicedconsonant/12-1-kaisya-F.mp3'),
    gaisya: require('../assets/sounds/voicedconsonant/12-2-gaisya-F.mp3'),
    mitsu: require('../assets/sounds/voicedconsonant/13-1-mitsu-F.mp3'),
    mizu: require('../assets/sounds/voicedconsonant/13-2-mizu-F.mp3'),
    shikai: require('../assets/sounds/voicedconsonant/14-1-shikai-F.mp3'),
    shigai: require('../assets/sounds/voicedconsonant/14-2-shigai-F.mp3'),
    kenkyuu: require('../assets/sounds/voicedconsonant/15-1-kenkyuu-F.mp3'),
    genkyuu: require('../assets/sounds/voicedconsonant/15-2-genkyuu-F.mp3'),
    // koudou: require('../assets/sounds/voicedconsonant/16-1-koudou-F.mp3'),
    // goudou: require('../assets/sounds/voicedconsonant/16-2-goudou-F.mp3'),
    // kantan: require('../assets/sounds/voicedconsonant/17-1-kantan-F.mp3'),
    // gantan: require('../assets/sounds/voicedconsonant/17-2-gantan-F.mp3'),
    jokin: require('../assets/sounds/voicedconsonant/18-1-jokin-F.mp3'),
    chokin: require('../assets/sounds/voicedconsonant/18-2-chokin-F.mp3'),
    // daikakumei: require('../assets/sounds/voicedconsonant/19-1-daikakumei-F.mp3'),
    // daigakumei: require('../assets/sounds/voicedconsonant/19-2-daigakumei-F.mp3'),
    // shoukai: require('../assets/sounds/voicedconsonant/20-1-shoukai-F.mp3'),
    // shougai: require('../assets/sounds/voicedconsonant/20-2-shougai-F.mp3'),
    taite: require('../assets/sounds/voicedconsonant/21-1-taite-F.mp3'),
    daite: require('../assets/sounds/voicedconsonant/21-2-daite-F.mp3'),
    // kankoku: require('../assets/sounds/voicedconsonant/22-1-kankoku-F.mp3'),
    // kangoku: require('../assets/sounds/voicedconsonant/22-2-kangoku-F.mp3')
    toite: require('../assets/sounds/voicedconsonant/23-1-toite-F.mp3'),
    toide: require('../assets/sounds/voicedconsonant/23-2-toide-F.mp3'),
    // kikai: require('../assets/sounds/voicedconsonant/24-1-kikai-F.mp3'),
    // gikai: require('../assets/sounds/voicedconsonant/24-2-gikai-F.mp3'),
    ito: require('../assets/sounds/voicedconsonant/25-1-ito-F.mp3'),
    ido: require('../assets/sounds/voicedconsonant/25-2-ido-F.mp3'),
    kachi: require('../assets/sounds/voicedconsonant/26-1-kachi-F.mp3'),
    kaji: require('../assets/sounds/voicedconsonant/26-2-kaji-F.mp3'),
    // kuchi: require('../assets/sounds/voicedconsonant/27-1-kuchi-F.mp3'),
    // guchi: require('../assets/sounds/voicedconsonant/27-2-guchi-F.mp3'),
    // kaikoku: require('../assets/sounds/voicedconsonant/28-1-kaikoku-F.mp3'),
    // gaikoku: require('../assets/sounds/voicedconsonant/28-2-gaikoku-F.mp3'),
    // long vowels
    biru: require('../assets/sounds/longvowel/01-biru-F.mp3'),
    biiru: require('../assets/sounds/longvowel/02-biiru-F.mp3'),
    syujin: require('../assets/sounds/longvowel/03-syujin-F.mp3'),
    syuujin: require('../assets/sounds/longvowel/04-syuujin-F.mp3'),
    soko: require('../assets/sounds/longvowel/05-soko-F.mp3'),
    sooko: require('../assets/sounds/longvowel/06-sooko-F.mp3'),
    ojisan: require('../assets/sounds/longvowel/07-ojisan-F.mp3'),
    ojiisan: require('../assets/sounds/longvowel/08-ojiisan-F.mp3'),
    sakka: require('../assets/sounds/longvowel/09-sakka-M.mp3'),
    sakkaa: require('../assets/sounds/longvowel/10-sakkaa-M.mp3'),
    kare: require('../assets/sounds/longvowel/11-kare-M.mp3'),
    karee: require('../assets/sounds/longvowel/12-karee-M.mp3'),
    kibo: require('../assets/sounds/longvowel/13-kibo-M.mp3'),
    kiboo: require('../assets/sounds/longvowel/14-kiboo-M.mp3'),
    kutsu: require('../assets/sounds/longvowel/15-kutsu-F.mp3'),
    kutsuu: require('../assets/sounds/longvowel/16-kutsuu-F.mp3'),
    sato: require('../assets/sounds/longvowel/17-sato-M.mp3'),
    satoo: require('../assets/sounds/longvowel/18-satoo-M.mp3'),
    kondo: require('../assets/sounds/longvowel/19-kondo-M.mp3'),
    kondoo: require('../assets/sounds/longvowel/20-kondoo-M.mp3'),
    // mora
    arigatou: require('../assets/sounds/mora/arigatou-ET.mp3'),
    chokkaku: require('../assets/sounds/mora/chokkaku-ET.mp3'),
    doshasaigai: require('../assets/sounds/mora/doshasaigai-ET.mp3'),
    gyogyou: require('../assets/sounds/mora/gyogyou-ET.mp3'),
    gyuunyuu: require('../assets/sounds/mora/gyuunyuu-ET.mp3'),
    joshu: require('../assets/sounds/mora/joshu-ET.mp3'),
    jouryuushu: require('../assets/sounds/mora/jouryuushu-ET.mp3'),
    jouryuusui: require('../assets/sounds/mora/jouryuusui-ET.mp3'),
    kippu: require('../assets/sounds/mora/kippu-ET.mp3'),
    konnichiha: require('../assets/sounds/mora/konnichiha-ET.mp3'),
    kotoba: require('../assets/sounds/mora/kotoba-ET.mp3'),
    kyouto: require('../assets/sounds/mora/kyouto-ET.mp3'),
    nihongo: require('../assets/sounds/mora/nihongo-ET.mp3'),
    sensei: require('../assets/sounds/mora/sensei-ET.mp3'),
    shoujozou: require('../assets/sounds/mora/shoujozou-ET.mp3'),
    teiryuujo: require('../assets/sounds/mora/teiryuujo-ET.mp3'),
    toukyou: require('../assets/sounds/mora/toukyou-ET.mp3'),
}

export default sounds